/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegendAdmin7f42c9RouteImport } from './routes/legend-admin-7f42c9'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendAdmin7f42c9Route = LegendAdmin7f42c9RouteImport.update({
  id: '/legend-admin-7f42c9',
  path: '/legend-admin-7f42c9',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legend-admin-7f42c9': typeof LegendAdmin7f42c9Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legend-admin-7f42c9': typeof LegendAdmin7f42c9Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legend-admin-7f42c9': typeof LegendAdmin7f42c9Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/legend-admin-7f42c9'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/legend-admin-7f42c9'
  id: '__root__' | '/' | '/legend-admin-7f42c9'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegendAdmin7f42c9Route: typeof LegendAdmin7f42c9Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legend-admin-7f42c9': {
      id: '/legend-admin-7f42c9'
      path: '/legend-admin-7f42c9'
      fullPath: '/legend-admin-7f42c9'
      preLoaderRoute: typeof LegendAdmin7f42c9RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegendAdmin7f42c9Route: LegendAdmin7f42c9Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
